"""Regenerate the gRPC stubs from `proto/toolmarket.proto`.

Generated code is not committed — a stub file is a build artifact, and a
checked-in one drifts from its `.proto` the first time someone edits the proto
and forgets to regenerate. The cost is that a fresh clone must run this before
the gRPC surface works; `toolmarket.grpc.server.import_stubs` says exactly that
in its error, which is the trade we chose: an actionable message beats a stale
stub that compiles and lies.

Two things this does that a bare `protoc` invocation does not:

1. Writes the `gen/` package marker, so the output is importable as
   `toolmarket.grpc.gen.toolmarket_pb2` rather than as a loose top-level module.

2. Rewrites the import in the generated `*_pb2_grpc.py`. `protoc` emits
   `import toolmarket_pb2 as ...` — an absolute import that only resolves if the
   generated directory happens to be on `sys.path`. Inside a package it must be
   relative, or importing it from anywhere else fails. Every Python gRPC
   project patches this line; this script is where that fact lives.

Run: `python tools/grpc_gen.py` (or `make grpc-gen`).
"""
from __future__ import annotations

import pathlib
import re
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
PROTO_DIR = ROOT / "proto"
PROTO = PROTO_DIR / "toolmarket.proto"
OUT_DIR = ROOT / "toolmarket" / "grpc" / "gen"
PKG = "toolmarket.grpc.gen"


def main() -> int:
    if not PROTO.exists():
        print(f"no proto at {PROTO}", file=sys.stderr)
        return 2

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    # A namespace package would work, but an explicit `__init__.py` makes the
    # generated tree behave identically under every loader, including the
    # zipimport path some deploys use.
    (OUT_DIR / "__init__.py").write_text(
        '"""Generated by tools/grpc_gen.py — do not edit by hand."""\n',
        encoding="utf-8")

    cmd = [
        sys.executable, "-m", "grpc_tools.protoc",
        f"-I{PROTO_DIR}",
        f"--python_out={OUT_DIR}",
        f"--grpc_python_out={OUT_DIR}",
        str(PROTO),
    ]
    print("+", " ".join(cmd))
    proc = subprocess.run(cmd, capture_output=True, text=True)
    if proc.returncode != 0:
        print(proc.stdout, file=sys.stderr)
        print(proc.stderr, file=sys.stderr)
        print("\ngrpcio-tools missing? pip install grpcio-tools", file=sys.stderr)
        return proc.returncode

    grpc_file = OUT_DIR / "toolmarket_pb2_grpc.py"
    text = grpc_file.read_text(encoding="utf-8")
    fixed = re.sub(
        r"^import toolmarket_pb2 as",
        f"from {PKG} import toolmarket_pb2 as",
        text,
        flags=re.MULTILINE,
    )
    if fixed != text:
        grpc_file.write_text(fixed, encoding="utf-8")
        print(f"rewrote the pb2 import in {grpc_file.name} to be package-relative")

    for f in sorted(OUT_DIR.glob("*.py")):
        print(f"  {f.relative_to(ROOT)}  {f.stat().st_size} B")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
